name: Terraform Apply
description: Run terraform init, plan and apply
inputs:
  working-directory:
    description: Terraform working directory
    required: true
runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Configure Terraform Plugin Cache
      shell: bash
      run: |
        mkdir -p ~/.terraform.d/plugin-cache
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc
    - name: Cache Terraform Plugins
      uses: actions/cache@v3
      with:
        path: ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-directory)) }}
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
    - name: Terraform Plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform plan -out=tfplan
    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform apply -auto-approve tfplan
